/**
 * @author Artem Lytvynov
 * @copyright Artem Lytvynov
 * @license Apache-2.0
 */

import { assert } from "@open-wc/testing";
import {
  niceNumeric,
  tickStep,
  ticksLog,
  ticksNumeric,
  ticksPow,
  ticksSymlog,
} from "./ticks-numeric";

/**
 * RFC §4.8 — the normative tick ladders, and §4.2 step 5's `nice`.
 *
 * A pure fixture table: no DOM, no computed style, no element, no
 * `fixture` import and no `await`. That is the module's own
 * invariant, and the grep
 * `grep -rn "document\.\|window\." src/hdvl/kernel/` is what keeps
 * it true.
 *
 * **Which cross-engine rule applies where** (plan rules 1, 2, 9):
 *
 * - Everything the integer-reciprocal form makes exact — `i /
 *   divisor`, `i · step` at a non-negative power, the `{1, 2, 5}`
 *   multiplier itself — is asserted with **exact `deepEqual`**.
 *   A `closeTo` here would discard the entire reason §4.8
 *   specifies the divisor form.
 * - `Math.pow(base, p)` for a small integer `p` is exact on all
 *   three engines, so the log ladder's powers are asserted
 *   **exactly** too. That is the one place rules 1 and 2 touch,
 *   and it is deliberate rather than an oversight: the ladder
 *   emits `base^p` and `k · base^p`, never a value that has been
 *   through `Math.log` on the way out. `logBase` is used only to
 *   pick the integer exponents.
 * - No assertion in this file needed `closeTo`.
 */

/* -------------------------------------------------------------- */
/* The numeric ladder                                             */
/* -------------------------------------------------------------- */

suite("hdvl/kernel/ticks-numeric — tickStep", () => {
  test("returns the divisor form at a negative power", () => {
    // The `divisor` is the point of this test, not the `step`:
    // 10 is an integer, so `i / 10` is exact for every i.
    assert.deepEqual(tickStep(0, 1, 10), {
      step: 0.1,
      divisor: 10,
      mult: 1,
      power: -1,
    });
  });

  test("returns the multiplied form at a non-negative power", () => {
    assert.deepEqual(tickStep(0, 100, 10), {
      step: 10,
      divisor: null,
      mult: 1,
      power: 1,
    });
  });

  // §4.8's multiplier chain, one domain per branch and one domain
  // exactly on each boundary. `power = floor(log10(raw))` puts
  // `err` in [1, 10), so the comparisons must be STRICT or the
  // `1` branch is unreachable and the ladder is permanently one
  // rung coarse. (RFC §4.8 amended 2026-08-20.)
  const MULTIPLIERS: [number, number, number, number][] = [
    // d1 (d0 = 0, count = 10), err, mult, step
    [60, 6, 10, 10],
    [50, 5, 5, 5], // boundary: err === 5 is NOT > 5
    [30, 3, 5, 5],
    [20, 2, 2, 2], // boundary: err === 2 is NOT > 2
    [15, 1.5, 2, 2],
    [10, 1, 1, 1], // boundary: err === 1 is NOT > 1
  ];

  for (const [d1, err, mult, step] of MULTIPLIERS) {
    test(`err ${err} selects multiplier ${mult}`, () => {
      const spec = tickStep(0, d1, 10);
      assert.strictEqual(spec.power, 0);
      assert.strictEqual(
        d1 / 10 / Math.pow(10, spec.power),
        err,
        "the fixture's err is what the ladder saw",
      );
      assert.strictEqual(spec.mult, mult);
      assert.strictEqual(spec.step, step);
    });
  }

  test("a degenerate domain yields an unusable step", () => {
    assert.strictEqual(tickStep(5, 5, 10).step, 0);
  });

  test("is the same for a descending domain", () => {
    assert.deepEqual(tickStep(10, 0, 10), tickStep(0, 10, 10));
  });
});

suite("hdvl/kernel/ticks-numeric — ticksNumeric", () => {
  test("ticks(0, 1, 10) is exact to the last bit", () => {
    // THE assertion R3 exists for. The multiplied form gives
    // 0.30000000000000004 at index 3 and 0.7000000000000001 at
    // index 7; `i / 10` gives the decimal literal exactly, on
    // chromium, firefox and webkit alike.
    assert.deepEqual(
      ticksNumeric(0, 1, 10),
      [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1],
    );
  });

  test("the multiplied form would not be", () => {
    // Not a claim about our code — a claim about why the divisor
    // form is in §4.8 at all. If this ever passes, the reason
    // for hand-writing the ladder is weaker than the RFC says.
    assert.notStrictEqual(3 * 0.1, 0.3);
    assert.strictEqual(3 / 10, 0.3);
  });

  test("nothing is generated by repeated addition", () => {
    // Behavioural, because the bug is invisible in a short
    // domain: a hundred-step ladder drifts by ~7e-16 under
    // `v += step` and loses its last element to the `<= hi`
    // test on whichever engine rounds the other way.
    const ticks = ticksNumeric(0, 1, 100);
    assert.lengthOf(ticks, 101);
    assert.strictEqual(ticks[100], 1);
    assert.strictEqual(ticks[7], 0.07);
    assert.strictEqual(ticks[29], 0.29);

    let accumulated = 0;
    for (let i = 0; i < 100; i++) {
      accumulated += 0.01;
    }
    assert.notStrictEqual(accumulated, ticks[100]);
  });

  test("a descending domain gives the same ticks", () => {
    // The ladder is over an interval, so [10, 0] and [0, 10]
    // are the same interval.
    assert.deepEqual(
      ticksNumeric(10, 0, 10),
      ticksNumeric(0, 10, 10),
    );
    assert.deepEqual(
      ticksNumeric(0, 10, 10),
      [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    );
  });

  test("a ladder crossing zero emits +0, never -0", () => {
    // The producer, stated as a platform fact so a later reader
    // sees where the normalisation earns its keep: the first
    // tick index is `Math.ceil(-0.4)`, which is -0.
    assert.isTrue(Object.is(Math.ceil(-0.4), -0));

    const ticks = ticksNumeric(-0.4, 2, 4);
    assert.deepEqual(ticks, [0, 1, 2]);
    // `strictEqual(x, 0)` passes for -0 and would prove nothing.
    assert.isTrue(Object.is(ticks[0], 0));
  });

  test("count is a target, never a promise", () => {
    // [0, 7] cannot be cut into 5 round intervals: raw is 1.4,
    // so the ladder rounds up to a step of 2 and stops at 6 —
    // four ticks for a target of five. Round values win over an
    // exact count (§4.8's first line).
    assert.deepEqual(ticksNumeric(0, 7, 5), [0, 2, 4, 6]);
  });

  test("a degenerate domain yields no ticks", () => {
    assert.deepEqual(ticksNumeric(5, 5, 10), []);
  });
});

suite("hdvl/kernel/ticks-numeric — niceNumeric", () => {
  const WIDENINGS: [number, number, number, number, number][] = [
    // d0, d1, count, nice d0, nice d1
    [0.6, 9.4, 10, 0, 10],
    [1, 9, 3, 0, 10],
    [0.1, 0.9, 2, 0, 1],
    [-4.2, 3.7, 10, -5, 4],
    [0, 10, 10, 0, 10],
  ];

  for (const [d0, d1, count, n0, n1] of WIDENINGS) {
    test(`nice([${d0}, ${d1}], ${count}) is [${n0}, ${n1}]`, () => {
      assert.deepEqual(niceNumeric(d0, d1, count), [n0, n1]);
    });
  }

  test("only ever widens", () => {
    // A property, not a point: `nice` moves endpoints OUTWARD
    // (§4.2 step 5), so the result must enclose the input in
    // both directions at every count.
    for (const [d0, d1, count] of WIDENINGS) {
      const [n0, n1] = niceNumeric(d0, d1, count);
      assert.isAtMost(n0, d0, `lower end of [${d0}, ${d1}]`);
      assert.isAtLeast(n1, d1, `upper end of [${d0}, ${d1}]`);
    }
  });

  test("is idempotent", () => {
    for (const [d0, d1, count] of WIDENINGS) {
      const once = niceNumeric(d0, d1, count);
      const twice = niceNumeric(once[0], once[1], count);
      assert.deepEqual(twice, once, `[${d0}, ${d1}]`);
    }
  });

  test("preserves a descending orientation", () => {
    assert.deepEqual(niceNumeric(9.4, 0.6, 10), [10, 0]);
  });

  test("emits +0, never -0, at a widened endpoint", () => {
    // `Math.ceil(-0.4)` again, this time through the upper
    // endpoint: step 0.5, so the index is ceil(-0.2 * 2).
    const nice = niceNumeric(-5, -0.2, 10);
    assert.deepEqual(nice, [-5, 0]);
    assert.isTrue(Object.is(nice[1], 0));
  });

  test("leaves a degenerate domain alone", () => {
    assert.deepEqual(niceNumeric(5, 5, 10), [5, 5]);
  });
});

/* -------------------------------------------------------------- */
/* The log, pow and symlog ladders                                */
/* -------------------------------------------------------------- */

suite("hdvl/kernel/ticks-numeric — ticksLog", () => {
  test("emits the powers of the base", () => {
    // Exact, not closeTo: `Math.pow(10, 0..3)` is 1, 10, 100,
    // 1000 on all three engines — an integer result at these
    // magnitudes is exactly representable and every engine's
    // pow returns it. See the file header.
    assert.deepEqual(ticksLog(1, 1000, 4, 10), [1, 10, 100, 1000]);
  });

  test("subdivides by {2, 5} when powers are fewer", () => {
    // Two powers against a target of six.
    assert.deepEqual(ticksLog(1, 10, 6, 10), [1, 2, 5, 10]);
  });

  test("subdivides a decade the domain only partly covers", () => {
    // No power of 10 lies in [1.5, 8] at all, so a
    // powers-inside-the-domain-only reading would emit nothing.
    // Subdivision walks the decades the domain TOUCHES.
    assert.deepEqual(ticksLog(1.5, 8, 6, 10), [2, 5]);
  });

  test("keeps every ceil(P / count)-th power when more", () => {
    // Seven powers, target three, so every third starting at
    // index 0 — the same thinning shape §4.8 gives ordinals.
    assert.deepEqual(ticksLog(1, 1e6, 3, 10), [1, 1000, 1000000]);
    // Four powers, target three: every second, which drops the
    // upper endpoint's decade. `count` is a target.
    assert.deepEqual(ticksLog(1, 1000, 3, 10), [1, 100]);
  });

  test("honours a non-10 base", () => {
    // {2, 5} is decimal-shaped: at base 2, `2 · 2^p` IS the next
    // power. The multipliers are filtered to `k < base`, so a
    // base-2 ladder is exactly the powers of two.
    assert.deepEqual(
      ticksLog(1, 64, 10, 2),
      [1, 2, 4, 8, 16, 32, 64],
    );
  });

  test("emits nothing for a non-positive domain", () => {
    // Honest, not defensive: §4.5's V2 diagnoses a log domain
    // touching zero at step 18, from the DOMAIN. The ladder
    // simply has no powers to offer there.
    assert.deepEqual(ticksLog(0, 100, 5, 10), []);
    assert.deepEqual(ticksLog(-10, 10, 5, 10), []);
  });
});

suite("hdvl/kernel/ticks-numeric — ticksPow", () => {
  test("reads as round values, because it is value space", () => {
    // The ladder chooses WHICH values to label, and in value
    // space the exponent has no say in that — which is why
    // `ticksPow` takes none. Exact, for the same reason
    // `ticksNumeric` is: it IS `ticksNumeric`.
    assert.deepEqual(ticksPow(0, 100, 5), [0, 20, 40, 60, 80, 100]);
    assert.deepEqual(ticksPow(0, 1, 10), ticksNumeric(0, 1, 10));
  });
});

suite("hdvl/kernel/ticks-numeric — ticksSymlog", () => {
  test("switches ladders at |v| = C and includes 0", () => {
    // Inside |v| <= 1 the numeric ladder: -1 … 1 by 0.5.
    // Outside it the log ladder, subdivided by {2, 5} and
    // mirrored through the origin. The join value 1 is
    // produced by both regions and de-duplicated.
    assert.deepEqual(
      ticksSymlog(-100, 100, 5, 1, 10),
      [
        -100, -50, -20, -10, -5, -2, -1, -0.5, 0, 0.5, 1, 2, 5, 10,
        20, 50, 100,
      ],
    );
  });

  test("always includes 0 when the domain spans it", () => {
    const ticks = ticksSymlog(-100, 100, 5, 1, 10);
    assert.isTrue(
      ticks.some((v) => Object.is(v, 0)),
      "a +0 tick, not a -0 one",
    );
  });

  test("honours a constant other than 1", () => {
    // C = 10, so [0, 10] is the numeric ladder and (10, 1000]
    // is the log one.
    assert.deepEqual(
      ticksSymlog(0, 1000, 5, 10, 10),
      [0, 2, 4, 6, 8, 10, 20, 50, 100, 200, 500, 1000],
    );
  });

  test("is ascending and duplicate-free", () => {
    const ticks = ticksSymlog(-1000, 1000, 6, 1, 10);
    const sorted = [...ticks].sort((a, b) => a - b);
    assert.deepEqual(ticks, sorted);
    assert.strictEqual(new Set(ticks).size, ticks.length);
  });

  test("stays inside a domain that never leaves C", () => {
    assert.deepEqual(
      ticksSymlog(-1, 1, 4, 1, 10),
      ticksNumeric(-1, 1, 4),
    );
  });
});
