/**
 * @author Artem Lytvynov
 * @copyright Artem Lytvynov
 * @license Apache-2.0
 */

import { Temporal } from "temporal-polyfill";

/**
 * The calendar-arithmetic seam (RFC 016/001 §4.8, §9.4).
 *
 * §9.4 fixes this module's surface at **four operations** — floor,
 * ceil, add, fields — and this is the only module under `src/` that
 * imports the polyfill. Two properties follow from that, and both
 * are load-bearing.
 *
 * 1. **The polyfill is a ponyfill VALUE, imported by name.** It is
 *    never the package's global-patch entry point, the module never
 *    reads the ambient binding off the global object, and there is
 *    no availability branch anywhere in it. That is not tidiness:
 *    the
 *    standard binding is present on chromium and firefox and
 *    **absent on webkit** (R4, measured), so an implementation that
 *    detected it would run *different calendar code on different
 *    engines* — the exact opposite of what a seam is for, and it
 *    would make every calendar assertion in the project a claim
 *    about three implementations that happen to agree today. Plan
 *    rule 5 enforces this against this file's **source text**,
 *    because no behavioural test can tell a polyfilled
 *    implementation from a native one.
 * 2. **Only epoch milliseconds cross the seam.** Every parameter
 *    and every return value is a `number` (or a plain record of
 *    them); no library object escapes. That is what makes §9.4's
 *    *"the day it lands everywhere, the swap is one import line and
 *    no call site changes"* true, and it is why every boundary this
 *    module produces can be asserted as an **exact integer** on all
 *    three engines rather than through a tolerance.
 *
 * **Everything is wall-clock arithmetic in `zone`, resolved with
 * `disambiguation: "compatible"`** (§4.8). The alternative —
 * exact-instant arithmetic — was measured at step 16 and is ruled
 * out by §4.8's own text: adding exact time can never land on a
 * boundary that does not exist, so §4.8's sentence about a
 * nonexistent boundary moving forward would describe nothing. It is
 * also visibly wrong on an axis. Across 2026-03-08 in
 * `America/New_York`, a `3h` rung generated by exact addition reads
 * `00:00 04:00 07:00 10:00 13:00`; generated in the zone it reads
 * `00:00 03:00 06:00 09:00 12:00`.
 *
 * **An unknown zone throws `RangeError`, and this module lets it
 * propagate.** A silent fall back to UTC would shift every boundary
 * in the chart by the intended zone's offset with nothing anywhere
 * reporting it — §1.5's silent-wrong-chart. Diagnosing a bad
 * authored zone belongs to the validator, at step 18; the kernel's
 * job is not to hide it. The same applies to a non-finite
 * `epochMs`: callers guard before they call, and
 * `ticks-calendar.ts` does.
 *
 * **This module is pure.** No DOM, no `getComputedStyle`, no import
 * side effect — `src/hdvl/kernel/` carries that rule as a
 * directory-wide invariant, asserted by grep. The one import is the
 * polyfill, which §9.4 permits here and nowhere else.
 *
 * @module hdvl/kernel/zone
 */

/**
 * §4.8's calendar units, coarsest last.
 *
 * The ladder's multiples (`5s`, `15m`, `3h`, `2d`, `3mo` …) are not
 * units — they are a count of one of these, which is why
 * {@link addUnits} takes an amount rather than the ladder taking
 * eighteen unit names.
 */
export type CalendarUnit =
  | "second"
  | "minute"
  | "hour"
  | "day"
  | "week"
  | "month"
  | "year";

/**
 * A wall-clock breakdown in a named zone.
 *
 * `offset` is here because it is the one field a caller cannot
 * re-derive from the others without crossing the seam again, and it
 * is what makes a DST transition observable to a test without the
 * test importing the polyfill.
 */
export interface ZonedFields {
  /** The ISO year. */
  year: number;
  /** The month, **1-12**. */
  month: number;
  /** The day of the month, 1-31. */
  day: number;
  /** The hour, 0-23. */
  hour: number;
  /** The minute, 0-59. */
  minute: number;
  /** The second, 0-59. */
  second: number;
  /** The millisecond, 0-999. */
  millisecond: number;
  /** The UTC offset in **minutes** at this instant. */
  offset: number;
}

/**
 * §4.8's disambiguation, stated once.
 *
 * In a gap it moves **forward** (so a nonexistent wall time
 * resolves to the instant the clock jumped to); in an overlap it
 * takes the **first**, earlier instant. Both halves were measured
 * at step 16 against `America/New_York` 2026.
 */
const DISAMBIGUATION = "compatible" as const;

/** Nanoseconds in a minute — the `offset` conversion. */
const NS_PER_MINUTE = 60_000_000_000;

/** The wall clock at `epochMs`, in `zone`. */
function plainOf(
  epochMs: number,
  zone: string,
): Temporal.PlainDateTime {
  return Temporal.Instant.fromEpochMilliseconds(epochMs)
    .toZonedDateTimeISO(zone)
    .toPlainDateTime();
}

/** The instant a wall clock denotes in `zone`, per §4.8. */
function anchor(plain: Temporal.PlainDateTime, zone: string): number {
  return plain.toZonedDateTime(zone, {
    disambiguation: DISAMBIGUATION,
  }).epochMilliseconds;
}

/** The wall clock truncated to the start of `unit`. */
function truncate(
  plain: Temporal.PlainDateTime,
  unit: CalendarUnit,
): Temporal.PlainDateTime {
  switch (unit) {
    case "second":
    case "minute":
    case "hour":
    case "day":
      return plain.round({
        smallestUnit: unit,
        roundingMode: "floor",
      });
    case "week": {
      // §4.8's `1w (ISO, Monday)`. `dayOfWeek` is 1 on Monday and
      // 7 on Sunday, so this is a no-op on a Monday and never
      // crosses forward.
      const day = plain.round({
        smallestUnit: "day",
        roundingMode: "floor",
      });
      return day.subtract({ days: day.dayOfWeek - 1 });
    }
    case "month":
      return plain
        .round({ smallestUnit: "day", roundingMode: "floor" })
        .with({ day: 1 });
    default:
      // `year`. `noImplicitReturns` wants a default rather than a
      // seventh named case.
      return plain
        .round({ smallestUnit: "day", roundingMode: "floor" })
        .with({ month: 1, day: 1 });
  }
}

/**
 * The boundary of `unit` containing `epochMs`, in `zone`.
 *
 * The wall clock is truncated and then re-anchored, so the result
 * is the boundary **as `compatible` resolves it**. That matters in
 * exactly one place: a zone whose DST gap swallows the boundary
 * itself — a few zones move their clocks at midnight — where the
 * boundary is the instant the gap moves it to, and so is *after*
 * the input rather than before. That is §4.8's rule, not an
 * approximation of it; no instant maps to a wall time inside a gap,
 * so the two can never disagree about which boundary an input
 * belongs to.
 *
 * A week floors to **ISO Monday** (§4.8).
 *
 * @param epochMs - The instant, in epoch milliseconds.
 * @param unit - The calendar unit to floor to.
 * @param zone - An IANA zone name. A caller with no zone passes
 *   `"UTC"` (§4.2); this module never defaults it.
 * @returns The boundary, in epoch milliseconds.
 */
export function floorTo(
  epochMs: number,
  unit: CalendarUnit,
  zone: string,
): number {
  return anchor(truncate(plainOf(epochMs, zone), unit), zone);
}

/**
 * The smallest boundary of `unit` at or after `epochMs`, in `zone`.
 *
 * @param epochMs - The instant, in epoch milliseconds.
 * @param unit - The calendar unit to ceil to.
 * @param zone - An IANA zone name.
 * @returns The boundary, in epoch milliseconds.
 */
export function ceilTo(
  epochMs: number,
  unit: CalendarUnit,
  zone: string,
): number {
  const floor = floorTo(epochMs, unit, zone);
  return floor >= epochMs ? floor : addUnits(floor, 1, unit, zone);
}

/**
 * `epochMs` plus `amount` × `unit` of **wall clock** in `zone`,
 * resolved with `disambiguation: "compatible"`.
 *
 * Wall-clock, not exact-instant: adding a day across a
 * spring-forward advances 23 hours of real time and still lands on
 * local midnight, and adding an hour across the same transition
 * lands on the wall clock's next hour rather than 3 600 000 ms
 * later. §4.8 requires the former for the `1d` rung and the latter
 * is what makes its nonexistent-boundary sentence mean anything.
 *
 * `amount` may be negative; the ladder uses that to snap a boundary
 * back onto its multiple.
 *
 * @param epochMs - The instant, in epoch milliseconds.
 * @param amount - How many `unit`s to add. May be negative.
 * @param unit - The calendar unit.
 * @param zone - An IANA zone name.
 * @returns The resulting instant, in epoch milliseconds.
 */
export function addUnits(
  epochMs: number,
  amount: number,
  unit: CalendarUnit,
  zone: string,
): number {
  const plain = plainOf(epochMs, zone);
  const moved =
    unit === "week"
      ? plain.add({ days: amount * 7 })
      : plain.add({ [`${unit}s`]: amount });
  return anchor(moved, zone);
}

/**
 * The wall-clock fields at `epochMs` in `zone`.
 *
 * @param epochMs - The instant, in epoch milliseconds.
 * @param zone - An IANA zone name.
 * @returns The broken-down wall clock, plus the UTC offset in
 *   minutes at that instant.
 */
export function fieldsOf(epochMs: number, zone: string): ZonedFields {
  const zoned =
    Temporal.Instant.fromEpochMilliseconds(
      epochMs,
    ).toZonedDateTimeISO(zone);
  return {
    year: zoned.year,
    month: zoned.month,
    day: zoned.day,
    hour: zoned.hour,
    minute: zoned.minute,
    second: zoned.second,
    millisecond: zoned.millisecond,
    offset: zoned.offsetNanoseconds / NS_PER_MINUTE,
  };
}
